# Extraccion del Archivo de Kaggle

**Puede tardar mucho tiempo**- igualmente el archivo lo puse dentro del directorio raw data.

In [2]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os

# Autenticar con Kaggle
api = KaggleApi()
api.authenticate()

print("✓ Autenticación con Kaggle completada")

Could not find kaggle.json. Make sure it's located in C:\Users\Martin Otero\.kaggle. Or use the environment method. See setup instructions at https://github.com/Kaggle/kaggle-api/

NameError: name 'exit' is not defined

In [3]:
# Descargar el archivo Combined_Flights_2022.csv desde Kaggle
import zipfile

dataset = 'robikscube/flight-delay-dataset-20182022'
file_name = 'Combined_Flights_2021.csv'

# Obtener la ruta actual del notebook
output_path = os.getcwd()

# Descargar el archivo específico
api.dataset_download_file(dataset, file_name, path=output_path)

print(f"✓ Descarga completada\n")

# El archivo se descarga como ZIP, vamos a descomprimirlo
zip_file = os.path.join(output_path, f'{file_name}.zip')

if os.path.exists(zip_file):
    print(f"Descomprimiendo {os.path.basename(zip_file)}...")
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(output_path)
    
    # Eliminar el archivo ZIP después de descomprimir
    os.remove(zip_file)
    print(f"✓ Archivo descomprimido y ZIP eliminado\n")

# Verificar que el archivo CSV existe
csv_path = os.path.join(output_path, file_name)
if os.path.exists(csv_path):
    file_size = os.path.getsize(csv_path)
    print(f"✓ Archivo {file_name} disponible")
    print(f"✓ Tamaño: {file_size / (1024**2):.2f} MB")
else:
    print(f"✗ Error: El archivo {file_name} no se encontró")

Dataset URL: https://www.kaggle.com/datasets/robikscube/flight-delay-dataset-20182022
✓ Descarga completada

Descomprimiendo Combined_Flights_2021.csv.zip...
✓ Archivo descomprimido y ZIP eliminado

✓ Archivo Combined_Flights_2021.csv disponible
✓ Tamaño: 2111.71 MB

In [4]:
# Mostrar las primeras filas del CSV
import pandas as pd
import os

csv_path = os.path.join(os.getcwd(), 'Combined_Flights_2021.csv')

if os.path.exists(csv_path):
    # Leer solo las primeras 100 filas para velocidad y mostrar head
    df = pd.read_csv(csv_path, low_memory=False, nrows=100)
    display(df.head())
else:
    print(f"✗ Archivo no encontrado: {csv_path}")

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2021-03-03,SkyWest Airlines Inc.,SGU,PHX,False,False,724,714.0,0.0,-10.0,...,724.0,813.0,5.0,843,-25.0,0.0,-2.0,0800-0859,2,0.0
1,2021-03-03,SkyWest Airlines Inc.,PHX,SGU,False,False,922,917.0,0.0,-5.0,...,940.0,1028.0,3.0,1040,-9.0,0.0,-1.0,1000-1059,2,0.0
2,2021-03-03,SkyWest Airlines Inc.,MHT,ORD,False,False,1330,1321.0,0.0,-9.0,...,1336.0,1445.0,16.0,1530,-29.0,0.0,-2.0,1500-1559,4,0.0
3,2021-03-03,SkyWest Airlines Inc.,DFW,TRI,False,False,1645,1636.0,0.0,-9.0,...,1703.0,1955.0,7.0,2010,-8.0,0.0,-1.0,2000-2059,4,0.0
4,2021-03-03,SkyWest Airlines Inc.,PHX,BFL,False,False,1844,1838.0,0.0,-6.0,...,1851.0,1900.0,3.0,1925,-22.0,0.0,-2.0,1900-1959,2,0.0

DESCARGA DE DATOS DE AEROPUERTOS

In [5]:
import pandas as pd

# Descargar directamente el CSV de OurAirports
url = "https://ourairports.com/data/airports.csv"
airports = pd.read_csv(url)

# Seleccionar columnas relevantes
airports = airports[['iata_code','name','latitude_deg','longitude_deg','iso_country']]
airports = airports.dropna(subset=['iata_code'])

airports.head(10)

,iata_code,name,latitude_deg,longitude_deg,iso_country
204,UTK,Utirik Airport,11.222219,169.851429,MH
410,OCA,Ocean Reef Club Airport,25.325399,-80.274803,US
632,CSE,Crested Butte Airpark,38.851918,-106.928341,US
888,CUS,Columbus Airport,31.823898,-107.629924,US
985,JCY,LBJ Ranch Airport,30.251801,-98.622498,US
1284,WLR,Loring Seaplane Base,55.601299,-131.636993,US
1385,NUP,Nunapitchuk Airport,60.905591,-162.440454,US
1403,PTC,Port Alice Seaplane Base,55.803000,-133.597000,US
1546,ICY,Icy Bay Airport,59.966269,-141.660118,US
1575,PPV,Port Protection Seaplane Base,56.328800,-133.610001,US

In [6]:
airports.shape

(9065, 5)

In [7]:
# Filtrar aeropuertos de Estados Unidos
airports_us = airports[airports['iso_country'] == 'US'].copy()

print("Total aeropuertos en US:", len(airports_us))
airports_us.head()

Total aeropuertos en US: 2037

,iata_code,name,latitude_deg,longitude_deg,iso_country
410,OCA,Ocean Reef Club Airport,25.325399,-80.274803,US
632,CSE,Crested Butte Airpark,38.851918,-106.928341,US
888,CUS,Columbus Airport,31.823898,-107.629924,US
985,JCY,LBJ Ranch Airport,30.251801,-98.622498,US
1284,WLR,Loring Seaplane Base,55.601299,-131.636993,US

Verifico cuantos valores unicos tengo y cuales para ver si son suficientes para la union con el dataset.

In [8]:
airports_us['iata_code'].nunique()

2037

In [9]:
airports_us['iata_code'].unique().tolist()

['OCA',
 'CSE',
 'CUS',
 'JCY',
 'WLR',
 'NUP',
 'PTC',
 'ICY',
 'PPV',
 'KKK',
 'MHS',
 'NIR',
 'GCT',
 'ELW',
 'LVD',
 'HGZ',
 'OTN',
 'TLF',
 'BZT',
 'HBH',
 'FAK',
 'BYW',
 'DRF',
 'BDF',
 'TEH',
 'VRS',
 'GDH',
 'ATT',
 'LIV',
 'PDB',
 'KOZ',
 'TNK',
 'WHD',
 'MNT',
 'TKI',
 'WKK',
 'WFB',
 'RFK',
 'NNK',
 'BKF',
 'BCS',
 'MMN',
 'SPQ',
 'TSS',
 'NYS',
 'BWL',
 'WYB',
 'CWS',
 'TEK',
 'DUF',
 'SSW',
 'FOB',
 'PUL',
 'CCD',
 'WMK',
 'AXB',
 'REE',
 'WDN',
 'WWP',
 'CHU',
 'UGS',
 'JID',
 'PSQ',
 'KLL',
 'SGW',
 'WTL',
 'TWA',
 'KCQ',
 'CEX',
 'SOL',
 'HED',
 'TWE',
 'KTH',
 'NKI',
 'CDL',
 'AOS',
 'BSW',
 'ALZ',
 'AQY',
 'HAE',
 'BNF',
 'BQV',
 'BYA',
 'PYS',
 'CGA',
 'CHP',
 'CIV',
 'CKD',
 'CKR',
 'CKU',
 'CKX',
 'CXC',
 'CYM',
 'CZN',
 'CZO',
 'IUA',
 'DJN',
 'DCK',
 'DHB',
 'DIO',
 'EDA',
 'EXI',
 'RGR',
 'FLT',
 'GNU',
 'HEY',
 'HGT',
 'HPV',
 'WKL',
 'HKB',
 'HWI',
 'HYL',
 'JLA',
 'JPN',
 'JRA',
 'JRB',
 'AMK',
 'BDX',
 'EUE',
 'KPT',
 'RLA',
 'FID',
 'HUD',
 'TWD',
 'MVM',
 'HCC',
 'AHD',
 'GCW',
 'CKE',
 'ROF',
 'CNE',
 'RSX',
 'COP',
 'CIL',
 'NWH',
 'IRB',
 'ODM',
 'GNF',
 'CHZ',
 'LTW',
 'USC',
 'AHF',
 'PCT',
 'CTO',
 'NRI',
 'GTP',
 'NLE',
 'GCD',
 'VLE',
 'FPY',
 'NTJ',
 'SBO',
 'JVI',
 'UCE',
 'GOL',
 'KKT',
 'PRW',
 'EGP',
 'BLD',
 'MFH',
 'ECA',
 'FMU',
 'OTS',
 'ROL',
 'CTK',
 'WPO',
 'ATE',
 'ASQ',
 'AAF',
 'ABE',
 'ABI',
 'ABQ',
 'ABR',
 'ABY',
 'ACB',
 'ACK',
 'ACT',
 'ACV',
 'ACY',
 'ADG',
 'ADT',
 'ADM',
 'ADS',
 'ADW',
 'KAE',
 'AEL',
 'AEX',
 'AFF',
 'WSG',
 'AFN',
 'AFO',
 'AFW',
 'AGC',
 'AGO',
 'AGS',
 'AHC',
 'AHH',
 'AHN',
 'AIA',
 'AID',
 'AIK',
 'AIO',
 'AIV',
 'AIZ',
 'AKO',
 'AKC',
 'ALB',
 'ALI',
 'ALM',
 'ALN',
 'ALO',
 'ALS',
 'ALW',
 'ALX',
 'AMA',
 'AMN',
 'AMW',
 'ANB',
 'AND',
 'SLT',
 'ANP',
 'ANQ',
 'ANW',
 'ANY',
 'AOH',
 'AOO',
 'APA',
 'APC',
 'APF',
 'APG',
 'APH',
 'APN',
 'APT',
 'APV',
 'ARA',
 'ARB',
 'ARG',
 'WHT',
 'AUZ',
 'ART',
 'ARV',
 'BFT',
 'ASE',
 'SPZ',
 'ASH',
 'ASL',
 'ASN',
 'AST',
 'ASX',
 'ASY',
 'ATL',
 'ATS',
 'ATW',
 'ATY',
 'AUG',
 'AUM',
 'AUN',
 'AUO',
 'AUS',
 'AUW',
 'AVL',
 'AVO',
 'AVP',
 'AVW',
 'AVX',
 'AWM',
 'AXG',
 'AXN',
 'AXS',
 'AXV',
 'AXX',
 'AYS',
 'TUH',
 'AZO',
 'BAB',
 'BAD',
 'BAF',
 'CLU',
 'BAM',
 'BBB',
 'BBD',
 'BKG',
 'BTN',
 'BBW',
 'BCB',
 'BCE',
 'BCT',
 'BDE',
 'BDG',
 'ILL',
 'BDL',
 'BDR',
 'WBU',
 'KBE',
 'BEC',
 'BED',
 'BEH',
 'BFD',
 'BFF',
 'BFI',
 'BFL',
 'BFM',
 'BFR',
 'BGD',
 'BGE',
 'BGM',
 'BGR',
 'BHB',
 'BHM',
 'BID',
 'BIE',
 'BIF',
 'BIH',
 'BIL',
 'BIS',
 'BIX',
 'BJC',
 'BJI',
 'BJJ',
 'BKD',
 'BKE',
 'BFK',
 'BKL',
 'BKT',
 'BKW',
 'BKX',
 'BLF',
 'BLH',
 'BLI',
 'BLM',
 'BLU',
 'BLV',
 'BMC',
 'BMG',
 'BMI',
 'BML',
 'BMT',
 'BNA',
 'BNG',
 'BNL',
 'BNO',
 'BNW',
 'BOI',
 'BOK',
 'BOS',
 'BOW',
 'HCA',
 'BPI',
 'WMH',
 'BPT',
 'BQK',
 'BRD',
 'BRL',
 'BRO',
 'BRY',
 'BTF',
 'BTL',
 'BTM',
 'TTO',
 'BTP',
 'BTR',
 'BTV',
 'BTY',
 'BUB',
 'BUF',
 'BUM',
 'BUR',
 'BFP',
 'BVO',
 'MVW',
 'BVX',
 'BVY',
 'BWC',
 'BWD',
 'BWG',
 'BWI',
 'WAH',
 'BWM',
 'BXA',
 'BXK',
 'NHZ',
 'BYG',
 'BYH',
 'BYI',
 'BYS',
 'BBC',
 'BZN',
 'XES',
 'PLY',
 'CLG',
 'CAD',
 'CAE',
 'CIG',
 'CAK',
 'CAO',
 'CAR',
 'CBE',
 'CBF',
 'CBK',
 'CBM',
 'KCC',
 'CCB',
 'CCR',
 'CCY',
 'LLX',
 'CDC',
 'CDH',
 'CDK',
 'CDN',
 'CDR',
 'CDS',
 'CDW',
 'CEA',
 'CEC',
 'CEF',
 'CEU',
 'CEV',
 'CEW',
 'CEY',
 'CEZ',
 'CFD',
 'TZC',
 'CFT',
 'CFV',
 'CGE',
 'CGF',
 'CGI',
 'CGS',
 'CGZ',
 'CHA',
 'CHK',
 'CHO',
 'CHS',
 'CIC',
 'CID',
 'CIN',
 'CIR',
 'CIU',
 'CKA',
 'CKB',
 'GRM',
 'CKM',
 'CKN',
 'CKV',
 'KCL',
 'CLE',
 'CLI',
 'CLK',
 'CLL',
 'CLM',
 'CLR',
 'CLS',
 'CLT',
 'CLW',
 'CMH',
 'CMI',
 'CMX',
 'CMY',
 'KCN',
 'CNH',
 'CNK',
 'CNM',
 'CNO',
 'CNU',
 'CNW',
 'CNY',
 'COD',
 'COE',
 'COF',
 'COI',
 'COM',
 'CON',
 'COS',
 'COT',
 'COU',
 'CPM',
 'CPR',
 'CPS',
 'HCW',
 'KCR',
 'CRE',
 'CRG',
 'CRP',
 'CLD',
 'CRS',
 'CRT',
 'CRW',
 'CRX',
 'CSG',
 'CSM',
 'CSQ',
 'CSV',
 'CTB',
 'CTY',
 'CTZ',
 'CUB',
 'CUH',
 'CVG',
 'HLI',
 'CKK',
 'CVN',
 'CVO',
 'CVS',
 'CWA',
 'KIP',
 'CWF',
 'CWI',
 'CXL',
 'CXO',
 'CSN',
 'HAR',
 'CYS',
 'CZK',
 'CZT',
 'VEX',
 'DAA',
 'DAB',
 'DAG',
 'DAL',
 'DAN',
 'DAY',
 'DBN',
 'DBQ',
 'DCA',
 'DCU',
 'DDC',
 'DEC',
 'DEH',
 'DEN',
 'DET',
 'DFI',
 'DFW',
 'DGL',
 'DGW',
 'DHN',
 'DHT',
 'DIK',
 'DKK',
 'DLL',
 'DLF',
 'DLH',
 'DLN',
 'DLS',
 'DMA',
 'DMN',
 'DMO',
 'DNL',
 'DNN',
 'DNS',
 'DNV',
 'DOV',
 'DPA',
 'DPG',
 'DRA',
 'DRI',
 'DRE',
 'DRO',
 'DRT',
 'DSM',
 'DSV',
 'DTA',
 'DTL',
 'DTN',
 'DSI',
 'DTW',
 'DUA',
 'DUC',
 'DUG',
 'DUJ',
 'DVL',
 'DVN',
 'NOT',
 'NSL',
 'DVT',
 'DWH',
 'DXR',
 'DYL',
 'DYS',
 'MIF',
 'CCG',
 'ESO',
 'WTR',
 'ALE',
 'BGT',
 'EAN',
 'EAR',
 'EAT',
 'EAU',
 'KEB',
 'EBS',
 'ECG',
 'ECP',
 'ECS',
 'EDE',
 'ETS',
 'EDW',
 'EED',
 'EEN',
 'EFD',
 'EFK',
 'EFW',
 'EGE',
 'EGI',
 'EGV',
 'KEK',
 'EKA',
 'EKI',
 'EKN',
 'EKO',
 'EKX',
 'ELA',
 'ELD',
 'ELK',
 'ELM',
 'ELN',
 'LYU',
 'ELP',
 'ELY',
 'ELZ',
 'EMM',
 'EMP',
 'EMT',
 'END',
 'ENL',
 'ENV',
 'ENW',
 'EOK',
 'EOS',
 'EPH',
 'EDK',
 'ERI',
 'ERR',
 'ERV',
 'ESC',
 'ESF',
 'ESN',
 'EST',
 'ESW',
 'ETB',
 'ETN',
 'EUF',
 'EUG',
 'EVM',
 'EVV',
 'EVW',
 'EWB',
 'EWK',
 'EWN',
 'EWR',
 'EYW',
 'WIB',
 'RBK',
 'FAF',
 'FAM',
 'FAR',
 'FAT',
 'FAY',
 'FBG',
 'FBL',
 'FBR',
 'FBY',
 'FCH',
 'FCM',
 'FCS',
 'FCY',
 'FDK',
 'FDR',
 'FDY',
 'FEP',
 'FET',
 'FFA',
 'FFL',
 'FFM',
 'FFO',
 'FFT',
 'MSC',
 'FRD',
 'FHU',
 'FKL',
 'FKN',
 'FLD',
 'FLG',
 'FLL',
 'FLO',
 'FLP',
 'FLV',
 'FLX',
 'FME',
 'FMH',
 'FMN',
 'FMY',
 'FNL',
 'FNT',
 'FOD',
 'FOE',
 'FOK',
 'FIL',
 'FPR',
 'FRG',
 'FRH',
 'FRI',
 'FRM',
 'FRR',
 'FSD',
 'FSI',
 'FSK',
 'FSM',
 'FST',
 'FSU',
 'FMS',
 'FTK',
 'FTW',
 'FTY',
 'FUL',
 'WFK',
 'FWA',
 'FXE',
 'FXY',
 'FYM',
 'FYV',
 'GAB',
 'GAD',
 'GAG',
 'GAI',
 'GBD',
 'GBG',
 'GBR',
 'GCC',
 'JDA',
 'GCK',
 'GCN',
 'GCY',
 'GDM',
 'GDV',
 'GDW',
 'GED',
 'GEG',
 'GEY',
 'GFA',
 'GFD',
 'GFK',
 'GFL',
 'GGE',
 'GGG',
 'GGW',
 'GHM',
 'IDH',
 'GIF',
 'GJT',
 'MEJ',
 'GKT',
 'GLD',
 'GLE',
 'GLH',
 'GLR',
 'GLS',
 'GLW',
 'GMU',
 'GNG',
 'GNT',
 'GNV',
 'GOK',
 'GON',
 'FCA',
 'GPT',
 'GPZ',
 'GQQ',
 'GRB',
 'GRD',
 'GRE',
 'GRF',
 'GRI',
 'GRK',
 'GRN',
 'GRR',
 'GSB',
 'GSH',
 'GSO',
 'GSP',
 'GTF',
 'GTG',
 'GTR',
 'GUC',
 'GUP',
 'GUS',
 'GUY',
 'GVE',
 'GVL',
 'GVT',
 'GWO',
 'GWS',
 'KGX',
 'GXY',
 'GDC',
 'PNX',
 'GYR',
 'GYY',
 'KGZ',
 'HAB',
 'HAF',
 'HAI',
 'HAO',
 'HBG',
 'HBR',
 'HDE',
 'HDN',
 'HEE',
 'MNZ',
 'HEZ',
 'HFD',
 'HFF',
 'HGR',
 'HHR',
 'HUJ',
 'HIB',
 'HIE',
 'HIF',
 'HII',
 'HIO',
 'HKA',
 'HKS',
 'HKY',
 'HLB',
 'HLC',
 'HLG',
 'HLN',
 'HLR',
 'HMN',
 'HMT',
 'HNB',
 'HSH',
 'HOB',
 'HON',
 'HOP',
 'HOT',
 'HOU',
 'HPN',
 'HPT',
 'HPY',
 'HQM',
 'HES',
 'HRL',
 'HRO',
 'HSB',
 'HNC',
 'THP',
 'HSI',
 'HSP',
 'HST',
 'HSV',
 'HTH',
 'HTL',
 'HTO',
 'HTS',
 'HTW',
 'HUA',
 'HUF',
 'HUL',
 'HUM',
 'HUT',
 'HVE',
 'HVN',
 'HVR',
 'HVS',
 'HWD',
 'HWO',
 'WSH',
 'HHH',
 'HYA',
 'HYR',
 'HYS',
 'HZL',
 'JFN',
 'IAB',
 'IAD',
 'IAG',
 'IAH',
 'KIB',
 'ICL',
 'ICT',
 'IDA',
 'IDG',
 'IDI',
 'IDP',
 'XPR',
 'IFA',
 'IFP',
 'IGM',
 'IJX',
 'IKK',
 'ILE',
 'ILG',
 'ILM',
 'ILN',
 'IML',
 'IMM',
 'MDN',
 'IMT',
 'IND',
 'INK',
 'INL',
 'INS',
 'INT',
 'INW',
 'IOW',
 'IPL',
 'IPT',
 'IRK',
 'IRS',
 'ISM',
 'ISO',
 'ISP',
 'ISQ',
 'ISW',
 'ITH',
 'AZA',
 'IWD',
 'ISS',
 'IWS',
 'JCI',
 'IYK',
 'SQA',
 'FRY',
 'JAC',
 'JAN',
 'JAS',
 'JAX',
 'JBR',
 'JCT',
 'JDN',
 'JEF',
 'JFK',
 'JHW',
 'GUF',
 'JLN',
 'JMS',
 'JOT',
 'USA',
 'JKV',
 'JST',
 'JVL',
 'JXN',
 'OSB',
 'KKB',
 'KIC',
 'KKL',
 'KLS',
 'KNB',
 'KKU',
 'DTH',
 'BXS',
 'RBF',
 'MYH',
 'TRH',
 'LAA',
 'LAF',
 'LAL',
 'LAM',
 'LAN',
 'LAR',
 'LAS',
 'LAW',
 'LAX',
 'LBB',
 'LBE',
 'LBF',
 'LBL',
 'LBT',
 'LJN',
 'LCH',
 'LCI',
 'LCK',
 'LCQ',
 'LDJ',
 'LDM',
 'LEB',
 'LEE',
 'LEM',
 'LEW',
 'LEX',
 'LFI',
 'LFK',
 'LFT',
 'LGA',
 'LGB',
 'LGC',
 'LGD',
 'LGF',
 'LGU',
 'LHV',
 'LIY',
 'LFN',
 'LIC',
 'LIT',
 'LKP',
 'LOW',
 'LKV',
 'CHL',
 'LMS',
 'LMT',
 ...]

In [10]:
airports_us.columns.tolist()

['iata_code', 'name', 'latitude_deg', 'longitude_deg', 'iso_country']

In [11]:
# Chequear nulos en el DataFrame "airports_us"
if 'airports_us' in globals():
    print("Resumen de nulos por columna:")
    null_counts = airports_us.isnull().sum()
    null_pct = (null_counts / len(airports_us) * 100).round(2)
    summary = pd.DataFrame({'null_count': null_counts, 'null_pct': null_pct, 'dtype': airports_us.dtypes})
    display(summary.sort_values('null_count', ascending=False))

    print("\nInformación general del DataFrame:")
    airports_us.info()

    any_null = airports_us.isnull().any().any()
    print(f"\n¿Hay filas con al menos un nulo? {any_null}")
    if any_null:
        print("Primeras 10 filas con al menos un nulo:")
        display(airports_us[airports_us.isnull().any(axis=1)].head(10))
else:
    print("Variable 'airports_us' no encontrada en el entorno. Verifica el nombre del DataFrame (p. ej. airports_us, airports, airports_us).")

Resumen de nulos por columna:

               null_count  null_pct    dtype
iata_code               0       0.0   object
name                    0       0.0   object
latitude_deg            0       0.0  float64
longitude_deg           0       0.0  float64
iso_country             0       0.0   object

Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
Index: 2037 entries, 410 to 84015
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iata_code      2037 non-null   object
 1   name           2037 non-null   object
 2   latitude_deg   2037 non-null   float64
 3   longitude_deg  2037 non-null   float64
 4   iso_country    2037 non-null   object
dtypes: float64(2), object(3)
memory usage: 95.5+ KB

¿Hay filas con al menos un nulo? False

In [12]:
airports_us.to_csv('raw data/airports.csv', index=False)

In [14]:
import hangarbay as hb
import pandas as pd

# 1) Cargar y preparar la base FAA (solo la primera vez tarda más)
hb.load_data()

# 2) Leer tu CSV de tail numbers (una columna, sin encabezado)
tails = pd.read_csv("raw data/tail_numbers.csv", header=None, names=["Tail_Number"], dtype=str)

# 3) Normalizar tail numbers: string, trim, upper, quitar caracteres raros
tails['Tail_Number'] = (
    tails['Tail_Number']
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(r'[^A-Z0-9]', '', regex=True)
)

# 4) Usar valores únicos para evitar búsquedas repetidas
unique_tails = tails['Tail_Number'].dropna().unique()

# 5) Buscar en FAA con hangarbay, acumulando resultados no vacíos
frames = []
for tn in unique_tails:
    try:
        df = hb.search(tn)
        if isinstance(df, pd.DataFrame) and not df.empty:
            frames.append(df)
    except Exception:
        # Si alguna búsqueda falla, la saltamos para que el proceso sea robusto
        pass

# 6) Concatenar todo y seleccionar columnas relevantes
if frames:
    results = pd.concat(frames, ignore_index=True)
else:
    results = pd.DataFrame(columns=['N-NUMBER','MODEL','YEAR MFR'])

# 7) Guardar el filtrado de FAA actualizado
results.to_csv("raw data/faa_tailnumbers_filtered.csv", index=False)

print("Filtrados:", results.shape[0], "registros guardados en faa_tailnumbers_filtered.csv")
print(results[['N-NUMBER','MODEL','YEAR MFR']].head())

✓ Data is up-to-date (7 days old)

Filtrados: 5498 registros guardados en faa_tailnumbers_filtered.csv

KeyError: "None of [Index(['N-NUMBER', 'MODEL', 'YEAR MFR'], dtype='object')] are in the [columns]"

In [15]:
read_faa = pd.read_csv("raw data/faa_tailnumbers_filtered.csv", dtype=str)
read_faa.head()

,n_number,serial_no,mfr_mdl_code,maker,model,engine_code,year_mfr,airworthiness_code,airworthiness_class,seats,...,status_code,reg_status,status_date,reg_expiration,is_deregistered,owner_name,city,state,zip,address
0,21144,145741,3260214,EMBRAER,EMB-145XR,54582,2003,5,Provisional,NaN,...,V,Valid,2025-01-06,2029-01-31,False,UNITED AIRLINES INC,CHICAGO,IL,60606,233 S WACKER DR
1,16170,14500850,3260214,EMBRAER,EMB-145XR,54582,2004,5,Provisional,NaN,...,V,Valid,2023-01-22,2027-05-31,False,UNITED AIRLINES INC,CHICAGO,IL,60606,233 S WACKER DR
2,11184,14500917,3260214,EMBRAER,EMB-145XR,54582,2005,5,Provisional,NaN,...,V,Valid,2023-01-22,2027-06-30,False,UNITED AIRLINES INC,CHICAGO,IL,60606,233 S WACKER DR
3,17146,145746,3260214,EMBRAER,EMB-145XR,03028,2003,5,Provisional,NaN,...,V,Valid,2023-07-07,2029-01-31,False,UNITED AIRLINES INC,CHICAGO,IL,60606,233 S WACKER DR
4,11191,14500935,3260214,EMBRAER,EMB-145XR,54582,2005,5,Provisional,NaN,...,V,Valid,2023-07-28,2027-11-30,False,UNITED AIRLINES INC,CHICAGO,IL,60606,233 S WACKER DR

In [16]:
read_faa['model'].nunique()

100

In [17]:
read_faa['model'].unique()

array(['EMB-145XR', 'CL-600-2C11', 'CL-600-2B19', 'EMB-145LR',
       'ERJ 170-200 LR', '737-7H4', '737-8H4', '737-800', '737-8',
       '737-700', '737-7BD', '737-79P', '737-7CT', '737-752', '737-76N',
       '737-79L', '737-7Q8', '737-7K9', '737-7K5', '737-76Q', '737-7L9',
       '737-7BK', '737-71B', '737-73V', 'ERJ 170-200 LL', 'CL-600-2D24',
       'ERJ 170-100SU', 'ERJ 170-100 SE', 'ERJ 170-100 LR', 'CL-600-2C10',
       'A321-231', '777-223', '787-9', '787-8', 'A321-253NX', 'A319-132',
       'A321-211', 'A319-112', '737-823', 'A320-232', 'A320-214',
       'A319-115', '777-323ER', '737-890', '737-9', '737-900ER',
       '737-790', '737-990ER', '737-8FH', 'ERJ 190-100 IGW', 'A321-271NX',
       'BD-500-1A11', 'A321-213', 'A319-114', 'A320-212', 'A320-211',
       '767-332', '767-432ER', '717-200', '737-932ER', '737-832',
       '757-231', '757-2Q8', '757-351', 'A330-302', 'BD-500-1A10',
       'A330-323', '737-8EH', 'A350-941', '757-26D', '757-251', '757-232',
       'A330-223', 'A330-941', 'A320-251N', 'A319-111', 'A330-243',
       'A321-271N', 'EMB-145', 'ERJ 170-100 STD', 'A320-271N',
       'DHC-8-402', '737-924ER', '737-824', '737-724', '757-224',
       'A319-131', '737-924', '787-10', '737-7V3', '777-300ER', '757-33N',
       '757-324', '777-224', '767-424ER', '767-322', '737-71Q', '767-3CB',
       '737-705', '777-222'], dtype=object)

In [18]:
read_faa.isnull().sum()

n_number                  0
serial_no                 0
mfr_mdl_code              0
maker                     0
model                     0
engine_code             119
year_mfr                131
airworthiness_code        0
airworthiness_class       0
seats                  5498
engines                5498
status_code               0
reg_status                0
status_date               0
reg_expiration            0
is_deregistered           0
owner_name                0
city                      0
state                     0
zip                       0
address                   0
dtype: int64

In [19]:
read_faa.columns.tolist()

['n_number',
 'serial_no',
 'mfr_mdl_code',
 'maker',
 'model',
 'engine_code',
 'year_mfr',
 'airworthiness_code',
 'airworthiness_class',
 'seats',
 'engines',
 'status_code',
 'reg_status',
 'status_date',
 'reg_expiration',
 'is_deregistered',
 'owner_name',
 'city',
 'state',
 'zip',
 'address']